library(magrittr)
library(dplyr)
library(data.table)
library(writexl)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(reshape2)
library(lme4)
library(lmerTest)
library(stringr)
library(QuantPsyc)
library(cowplot)
library(ggsignif) 
library(lme4)
install.packages("devtools") # Devtools is a package which allows to do this.
devtools::install_github("dustinfife/flexplot")
library(flexplot)
library(nlme)
library(tidyverse)
library(lme4)
library(ggsci)
library(cowplot)
library(sjPlot)


a<-lm(cbcl_scr_syn_internal_r_4~averaged_Fluidity+Age_4+truesex_1+race_ethnicity_1, data= AHHHHflipped)
b<-lm(cbcl_scr_syn_external_r_4~averaged_Fluidity+Age_4+truesex_1+race_ethnicity_1, data= AHHHHflipped)

print(summary(b))

print(tab_model(b,show.stat = TRUE,string.stat = "T-Value", auto.label = FALSE, pred.labels = c("Intercept","Averaged Gender Fluidity", "Ever Gender Diverse", "Age", "Sex", "Race/Ethnicity")))
