library(magrittr)
library(dplyr)
library(data.table)
library(writexl)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(reshape2)
library(lme4)
library(lmerTest)
library(stringr)
library(QuantPsyc)
library(cowplot)
library(ggsignif) 
library(lme4)
install.packages("devtools") # Devtools is a package which allows to do this.
devtools::install_github("dustinfife/flexplot")
library(flexplot)
library(nlme)
library(tidyverse)
library(lme4)
library(ggsci)
library(cowplot)
library(sjPlot)
library(jtools)

martin = lmer(cbcl_scr_syn_internal_r~Gender_Dissonance+I(Gender_Dissonance^2)+Age+truesex+race_ethnicity+(1+Gender_Dissonance|src_subject_id), data = Glep_in_range)

summary(martin)
print(tab_model(martin,show.stat = TRUE,string.stat = "T-Value", auto.label = FALSE, pred.labels = c("Intercept","Gender Dissonance","Gender Dissonance Squared", "Age", "Sex", "Race/Ethnicity")))
print(sjPlot::plot_model(martin,type = "pred",terms = "Gender_Dissonance[all]",show.data = FALSE,show.p = TRUE, ci_level = 0.95, colors = "#00BFC4")+ ggplot2::ylim(3,9))
print(jtools::export_summs(martin, statistics = "all"))

