library(magrittr)
library(dplyr)
library(data.table)
library(writexl)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(reshape2)
library(lme4)
library(lmerTest)
library(stringr)
library(QuantPsyc)
library(cowplot)
library(ggsignif) 

Logistic_Regression_suicide_attempt <- glm(ever_attempt_4~averaged_Fluidity+Age_4+truesex_1+race_ethnicity_1, data= AHHHH_suicidetwinssibsonlychoseone,family = binomial(link = "logit"))
print(tab_model(Logistic_Regression_suicide_attempt,show.stat = TRUE,string.stat = "T-Value", auto.label = FALSE, pred.labels = c("Intercept","Averaged Gender Fluidity", "Age", "Sex", "Race/Ethnicity")))
print(summ(Logistic_Regression_suicide_attempt))
print(lm.beta(Logistic_Regression_suicide_attempt))